export const docTypes = [
  'Solicitation / Financial Assistance',
  'Medical Assistance',
  'Courtesy Call',
  'Invitation',
  'Infrastructure Request',
  'Request Endorsement/Applicants',
  'Others',
]

export const docRouting = [
  'Received at Admin',
  'Received at Mayors Office',
  'Forwarded to Accounting',
  'Forwarded to Admin',
  'Forwarded to Agriculture',
  'Forwarded to Assesors',
  'Forwarded to Atty. Kate Daytec Aventajado',
  'Forwarded to BAC',
  'Forwarded to BFP',
  'Forwarded to BJMP',
  'Forwarded to Budget',
  'Forwarded to COA',
  'Forwarded to DCO',
  'Forwarded to DILG',
  'Forwarded to Engineering',
  'Forwarded to GSO',
  'Forwarded to GSO DESIGNEE - Raphael Claude Rousseau',
  'Forwarded to HR',
  'Forwarded to LCR',
  'Forwarded to Mayors Office',
  'Forwarded to MEDO',
  'Forwarded to MDRRMO',
  'Forwarded to MPDO',
  'Forwarded to MSWDO',
  'Forwarded to Permit Div',
  'Forwarded to PDAO',
  'Forwarded to PNP',
  'Forwarded to RHU',
  'Forwarded to Sentro sa Pagserbis YU',
  'Forwarded to SB Office',
  'Forwarded to Subanen Affairs',
  'Forwarded to Tourism',
  'Forwarded to Treasurers',
]

export const documentTypes = [
  { type: 'Business Permit', shortcut: 'BUSS-PER' },
  { type: 'Case', shortcut: 'CASE' },
  { type: 'Certification', shortcut: 'CERT' },
  { type: 'Contract of Service', shortcut: 'COS' },
  { type: 'Cheque', shortcut: 'CHQ' },
  { type: 'DTR', shortcut: 'DTR' },
  { type: 'Disbursement Voucher', shortcut: 'DV' },
  { type: 'Executive Order', shortcut: 'EO' },
  { type: 'IPCR/OPCR', shortcut: 'IPCR/OPCR' },
  { type: 'Letters', shortcut: 'LETTER' },
  { type: 'Leave', shortcut: 'LEAVE' },
  { type: 'Liquidation', shortcut: 'LIQUIDATION' },
  { type: 'Retirement', shortcut: 'RET' },
  { type: 'Memorandum Order', shortcut: 'MEMO' },
  { type: 'Notice', shortcut: 'NOTICE' },
  { type: 'Notice of Violation', shortcut: 'NOTI-VIOL' },
  { type: 'Office Order', shortcut: 'OFC-ORD' },
  { type: 'Other Documents', shortcut: 'OTR-DOC' },
  { type: 'Order of Payment', shortcut: 'ORD-PYMT' },
  { type: 'Ordinance', shortcut: 'ORD' },
  { type: 'OBR', shortcut: 'OBR' },
  { type: 'OBR/Payroll', shortcut: 'OBR/PYRL' },
  { type: 'Permit', shortcut: 'PERMIT' },
  { type: 'Project', shortcut: 'PROJ' },
  { type: 'PR/OBR', shortcut: 'PR/OBR' },
  { type: 'Purchase Request', shortcut: 'PR' },
  { type: 'Proposal', shortcut: 'PRPSL' },
  { type: 'Purchase Order', shortcut: 'PO' },
  { type: 'OBR/Reimbursement', shortcut: 'OBR/REIMB' },
  { type: 'Resolution', shortcut: 'RESO' },
  { type: 'Reports', shortcut: 'REPORT' },
  { type: 'Salary Loan', shortcut: 'SAL-LOAN' },
  { type: 'Show Cause', shortcut: 'SHW-CAUSE' },
  { type: 'Special Order', shortcut: 'SO' },
  { type: 'Travel Order', shortcut: 'TO' },
]

export const statusList = [
  { status: 'Approved', color: '#287f00' },
  { status: 'Canceled', color: '#e02626' },
  { status: 'Disapproved', color: '#e02626' },
  { status: 'For File', color: '#997c00' },
  { status: 'For Further Instruction', color: '#997c00' },
  { status: 'Open', color: '#2154db' },
  { status: 'Resolved', color: '#a44508' },
]

export const superAdmins = ['berlcamp@gmail.com', 'arfel@ddm.com']

export const risOffices = [
  'DILG',
  'MEO',
  'GREENVILLE',
  'MAO',
  'ACCOUNTING',
  'MSOA',
  'BJMP',
  'MPDO',
  'MMO',
  'MSWD',
  'TOURISM',
  'PNP',
  'DWD',
  'KALIPI',
  'ASSESOR',
  'GSO',
  'MDRRMO',
  'MENRO',
  'SR CITIZEN',
  'BPLO',
  'PDAO',
  'MTO',
  'MCR',
  'DOCO',
  'MHO',
  'LEGAL',
  'PESO',
  'MYDO',
  'OTP',
  'MEDO',
]

export const profileCategories = ['', 'A', 'B', 'C', 'UC']

export const profilePositions = [
  'Barangay Chairman',
  'Barangay Councilor',
  'Barangay Secretary',
  'Barangay Treasurer',
  'BHW',
  'BPAT',
  'Government Employee',
  'LGU Employee',
  'Undefined',
]

export const barangays = [
  'BAG-ONG KAUSWAGAN',
  'BAG-ONG SILANG',
  'BAGONG VALENCIA',
  'BUCAYAN',
  'CALUMANGGI',
  'CANIBONGAN',
  'CARIDAD',
  'DANLUGAN',
  'DAPIWAK',
  'DATU TUTUKAN',
  'DILUD',
  'DITULAN',
  'DULIAN',
  'DULOP',
  'GUINTANANAN',
  'GUITRAN',
  'GUMPINGAN',
  'LA FORTUNA',
  'LABANGON',
  'LIBERTAD',
  'LICABANG',
  'LIPAWAN',
  'LOWER LANDING',
  'LOWER TIMONAN',
  'MACASING',
  'MAHAYAHAY',
  'MALAGALAD',
  'MANLABAY',
  'MARALAG',
  'MARANGAN',
  'NEW BASAK',
  'SAAD',
  'SALVADOR',
  'SAN JUAN',
  'SAN PABLO',
  'SAN PEDRO',
  'SAN VICENTE',
  'SINONOK',
  'SINOTE',
  'SUNOP',
  'TAGUN',
  'TAMURAYAN',
  'UPPER LANDING',
  'UPPER TIMONAN',
]

export const services = ['TUPAD Beneficiary', 'DSWD Food For Work']
