-- Vehicle reservations: date-range support + multiple vehicles per reservation.
--
-- 1. `date_end` / `time_end` turn a reservation into a span instead of a single
--    departure moment. Existing rows are backfilled to a same-day span.
-- 2. `ddm_reservation_vehicle_assignments` lets one reservation hold several
--    vehicles. `ddm_reservations.vehicle_id` is kept in sync with the first
--    assigned vehicle so older reads keep working.

ALTER TABLE public.ddm_reservations
ADD COLUMN IF NOT EXISTS date_end date;

ALTER TABLE public.ddm_reservations
ADD COLUMN IF NOT EXISTS time_end text;

UPDATE public.ddm_reservations
SET date_end = date
WHERE date_end IS NULL;

-- The junction table mirrors the id types of the tables it references, so this
-- works whether those primary keys are bigint, int or uuid.
DO $$
DECLARE
  reservation_id_type text;
  vehicle_id_type text;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
  INTO reservation_id_type
  FROM pg_attribute a
  WHERE a.attrelid = 'public.ddm_reservations'::regclass
    AND a.attname = 'id';

  SELECT format_type(a.atttypid, a.atttypmod)
  INTO vehicle_id_type
  FROM pg_attribute a
  WHERE a.attrelid = 'public.ddm_reservation_vehicles'::regclass
    AND a.attname = 'id';

  EXECUTE format(
    $ddl$
      CREATE TABLE IF NOT EXISTS public.ddm_reservation_vehicle_assignments (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reservation_id %s NOT NULL
          REFERENCES public.ddm_reservations (id) ON DELETE CASCADE,
        vehicle_id %s NOT NULL
          REFERENCES public.ddm_reservation_vehicles (id) ON DELETE CASCADE,
        created_at timestamptz NOT NULL DEFAULT now(),
        UNIQUE (reservation_id, vehicle_id)
      )
    $ddl$,
    reservation_id_type,
    vehicle_id_type
  );
END
$$;

CREATE INDEX IF NOT EXISTS ddm_reservation_vehicle_assignments_vehicle_idx
ON public.ddm_reservation_vehicle_assignments (vehicle_id);

CREATE INDEX IF NOT EXISTS ddm_reservation_vehicle_assignments_reservation_idx
ON public.ddm_reservation_vehicle_assignments (reservation_id);

-- Overlap lookups scan by date span.
CREATE INDEX IF NOT EXISTS ddm_reservations_date_span_idx
ON public.ddm_reservations (date, date_end);

-- Backfill: every existing reservation becomes a single-vehicle assignment.
INSERT INTO public.ddm_reservation_vehicle_assignments (reservation_id, vehicle_id)
SELECT r.id, r.vehicle_id
FROM public.ddm_reservations r
WHERE r.vehicle_id IS NOT NULL
ON CONFLICT (reservation_id, vehicle_id) DO NOTHING;
